provenance:
  yaml authors:
  - author: Felicity Anderson
    email: Felicity.Anderson@ed.ac.uk
  - author: Sophie Winterbourne
    email: '...'
  DOI: http://dx.doi.org/10.1126/sciadv.aba1306
  GEO: GSE134152
  date run: 2021-02-23
  notes: Ribosome profiling datasets of Saccharomyces cerevisiae grown under glucose
    restriction conditions.
  reference: Life span extension by glucose restriction is abrogated by methionine
    supplementation - Cross-talk between glucose and methionine and implication of
    methionine as a key regulator of life span, Zou et al 2020.
  riboviz-version: 2.0 | COMMIT e94a909c70942cb428450a3b98edef1614143c18
  website: null

adapters: CTGTAGGCACCATCAAT
aligner: hisat2
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 250
build_indices: true
cmd_file: run_riboviz_Z-Sc_2020.sh
codon_positions_file: data/yeast_codon_pos_i200.RData
count_reads: true
count_threshold: 64
dataset: Z-Sc_2020
dedup_stats: false
dedup_umis: false
dir_in: Z-Sc_2020/input
dir_index: Z-Sc_2020/index
dir_logs: Z-Sc_2020/logs
dir_out: Z-Sc_2020/output
dir_tmp: Z-Sc_2020/tmp
do_pos_sp_nt_freq: true
extract_umis: false
features_file: data/yeast_features.tsv
fq_files: # fastq files to be processed, relative to dir_in
  SD-sample3-1: SRR9670816.fastq.gz # SD (2% glucose)
  SD-sample3-2: SRR9670817.fastq.gz # SD (2% glucose)
  GR-sample4-1: SRR9670818.fastq.gz # GR (0.05% glucose)
  GR-sample4-2: SRR9670819.fastq.gz # GR (0.05% glucose)
  SD-sample7: SRR9670822.fastq.gz # SD (2% glucose)
  GR-sample8: SRR9670823.fastq.gz # GR (0/05% glucose)
group_umis: false
is_riboviz_gff: true
job_email: null
job_email_events: beas
job_memory: 20G
job_name: riboviz
job_num_cpus: 10
job_parallel_env: sharedmem
job_runtime: '18:00:00'
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
nextflow_dag_file: nextflow-dag.html
nextflow_report_file: nextflow-report.html
nextflow_timeline_file: nextflow-timeline.html
nextflow_trace_file: nextflow-trace.tsv
nextflow_work_dir: Z-Sc_2020/work
num_processes: 16
orf_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa
orf_gff_file: ../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3
orf_index_prefix: yeast_CDS_w_250
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa
rrna_index_prefix: yeast_rRNA
sample_sheet: null
samsort_memory: 768M
secondary_id: null
skip_inputs: false
stop_in_cds: false
t_rna_file: data/yeast_tRNAs.tsv
trim_5p_mismatches: true
umi_regexp: null
validate_only: false
